name: Daily Esperanto Word Bot

on:
  schedule:
    - cron: '6,12,18,24,30,36,42,48,54,0 * * * *'
  workflow_dispatch:

jobs:
  send-words:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
    - name: Run bot script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: npm start